modules/admin/controllers/AboutController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\About;
use app\models\search\AboutSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AboutController implements the CRUD actions for About model.
 */
class AboutController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all About models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AboutSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single About model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new About model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new About();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing About model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing About model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the About model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return About the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = About::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

modules/admin/controllers/DefaultController.php
<?php

namespace app\modules\admin\controllers;

use mdm\admin\models\form\Login;
use Yii;
use yii\web\Controller;

/**
 * Default controller for the `admin` module
 */
class DefaultController extends Controller
{
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->getUser()->isGuest) {
            return $this->goHome();
        }

        $this->layout = 'login';
        $model = new Login();

        if ($model->load(Yii::$app->getRequest()->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }
}

modules/admin/controllers/HeaderController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Header;
use app\models\search\HeaderSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * HeaderController implements the CRUD actions for Header model.
 */
class HeaderController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Header models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new HeaderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Header model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Header model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Header();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Header model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Header model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Header model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Header the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Header::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

modules/admin/controllers/PolicyController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Policy;
use app\models\search\PolicySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PolicyController implements the CRUD actions for Policy model.
 */
class PolicyController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Policy models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PolicySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Policy model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Policy model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Policy();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Policy model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Policy model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Policy model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Policy the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Policy::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

modules/admin/controllers/SocialsController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Socials;
use app\models\search\SocialsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SocialsController implements the CRUD actions for Socials model.
 */
class SocialsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Socials models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SocialsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Socials model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Socials model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Socials();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Socials model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Socials model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Socials model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Socials the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Socials::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

modules/admin/views/default/index.php
<?php
use yii\helpers\Url;

?>
<div class="row">
    <div class="col-lg-12">
        <div class="card p-30">
            <div class="media home-images">
                <div class="img-header">
                    <a href="<?= Url::to(['header/view', 'id' => 1]) ?>">
                        <img src="/images/green/header.jpg" onmouseover="hoverHeader(this);" onmouseout="unhoverHeader(this);"/>
                    </a>
                </div>
                <div class="img-about">
                    <a href="<?= Url::to(['about/view','id' => 1]) ?>">
                        <img src="/images/green/about.jpg" onmouseover="hoverAbout(this);" onmouseout="unhoverAbout(this);" />
                    </a>
                </div>
                <div class="img-categories">
                    <a href="<?= Url::to(['category/index']) ?>">
                        <img src="/images/green/categories.jpg" onmouseover="hoverCategories(this);" onmouseout="unhoverCategories(this);" />
                    </a>
                </div>
                <div class="img-products">
                    <a href="<?= Url::to(['products/index']) ?>">
                        <img src="/images/green/products.jpg" onmouseover="hoverProducts(this);" onmouseout="unhoverProducts(this);" />
                    </a>
                </div>
                <div class="img-discounts">
                    <a href="<?= Url::to(['discounts/index']) ?>">
                        <img src="/images/green/discounts.jpg" onmouseover="hoverDiscounts(this);" onmouseout="unhoverDiscounts(this);" />
                    </a>
                </div>
                <div class="img-policy">
                    <a href="<?= Url::to(['policy/index']) ?>">
                        <img src="/images/green/policy.jpg" onmouseover="hoverPolicy(this);" onmouseout="unhoverPolicy(this);" />
                    </a>
                </div>
                <div class="img-projects">
                    <a href="<?= Url::to(['projects/index']) ?>">
                        <img src="/images/green/projects.jpg" onmouseover="hoverProjects(this);" onmouseout="unhoverProjects(this);" />
                    </a>
                </div>
                <div class="img-socials">
                    <a href="<?= Url::to(['socials/index']) ?>">
                        <img src="/images/green/socials.jpg" onmouseover="hoverSocials(this);" onmouseout="unhoverSocials(this);" />
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Start Page Content -->
<div class="row">
    <div class="col-md-6">
        <div class="card p-30">
            <div class="media">

            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card p-30">
            <div class="media">

            </div>
        </div>
    </div>
</div>

<script>
//    Header
    function hoverHeader(element) {
        element.setAttribute('src', '/images/green/header_hover.JPG');
    }
    function unhoverHeader(element) {
        element.setAttribute('src', '/images/green/header.JPG');
    }
//    About
    function hoverAbout(element) {
        element.setAttribute('src', '/images/green/about_hover.JPG');
    }
    function unhoverAbout(element) {
        element.setAttribute('src', '/images/green/about.JPG');
    }
//    Categories
    function hoverCategories(element) {
        element.setAttribute('src', '/images/green/categories_hover.JPG');
    }
    function unhoverCategories(element) {
        element.setAttribute('src', '/images/green/categories.JPG');
    }
//    Products
    function hoverProducts(element) {
        element.setAttribute('src', '/images/green/products_hover.JPG');
    }
    function unhoverProducts(element) {
        element.setAttribute('src', '/images/green/products.JPG');
    }

//    Discounts
    function hoverDiscounts(element) {
        element.setAttribute('src', '/images/green/discounts_hover.JPG');
    }
    function unhoverDiscounts(element) {
        element.setAttribute('src', '/images/green/discounts.JPG');
    }
//    Policy
    function hoverPolicy(element) {
        element.setAttribute('src', '/images/green/policy_hover.JPG');
    }
    function unhoverPolicy(element) {
        element.setAttribute('src', '/images/green/policy.JPG');
    }
//    Projects
    function hoverProjects(element) {
        element.setAttribute('src', '/images/green/projects_hover.JPG');
    }
    function unhoverProjects(element) {
        element.setAttribute('src', '/images/green/projects.JPG');
    }
//    Socials
    function hoverSocials(element) {
        element.setAttribute('src', '/images/green/socilas_hover.JPG');
    }
    function unhoverSocials(element) {
        element.setAttribute('src', '/images/green/socials.JPG');
    }
</script>

modules/admin/views/default/login.php
<?php
/**
 * Created by PhpStorm.
 * User: Farhodjon
 * Date: 09.03.2018
 * Time: 16:50
 */

use yii\bootstrap\ActiveForm;

$this->title = 'Login to admin panel';

?>
<div class="unix-login">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-4">
                <div class="login-content card">
                    <div class="login-form">
                        <h4>Login</h4>
                        <?php $form = ActiveForm::begin() ?>
                        <?= $form->field($model, 'username')->textInput() ?>
                        <?= $form->field($model, 'password')->passwordInput() ?>
                        <?= $form->field($model, 'rememberMe')->checkbox() ?>
                        <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30">Sign in</button>
                        <?php ActiveForm::end() ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>